name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 22.14.0
      uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
    - name: Install dependencies
      run: npm i
    - name: Run integration tests
      run: npm test

  deploy:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    permissions:
      deployments: write

    needs: build-test

    steps:
      - name: Deploy on Production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
